spring:
  cloud:
    aws:
      credentials:
        access-key:  ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ap-south-1
      stack:
        auto: false

application:
  bucket:
    name: atharsbucket